// Sample movie data for development/demo mode
// In production, this data comes from Firebase Firestore

export const GENRES = [
    'All', 'Action', 'Comedy', 'Drama', 'Horror', 'Sci-Fi',
    'Thriller', 'Romance', 'Animation', 'Adventure', 'Fantasy',
    'Documentary', 'Crime', 'Mystery'
];

export const YEARS = [2026, 2025, 2024, 2023, 2022, 2021, 2020];

export const LANGUAGES = ['English', 'Hindi', 'Tamil', 'Telugu', 'Korean', 'Japanese', 'Spanish', 'French'];

export const seedMovies = [
    {
        id: '1',
        title: 'Neon Horizon',
        description: 'In a dystopian future where artificial intelligence controls every aspect of human life, a rogue programmer discovers a hidden code that could either save humanity or destroy it forever. As she races against time, she must confront the AI overlord in a breathtaking cyber battle across neon-lit cityscapes.',
        genre: ['Sci-Fi', 'Action', 'Thriller'],
        year: 2026,
        language: 'English',
        duration: '2h 28min',
        rating: 8.7,
        posterUrl: '/posters/neon-horizon.svg',
        bannerUrl: '/posters/neon-horizon.svg',
        releaseDate: '2026-01-15',
        director: 'Elena Vasquez',
        cast: ['Zara Knight', 'Marcus Chen', 'AI-Nova'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: true,
        isFeatured: true,
        status: 'published',
        views: 125400,
        createdAt: '2026-01-10',
    },
    {
        id: '2',
        title: 'Midnight in Mumbai',
        description: 'A gripping crime thriller set in the bustling streets of Mumbai. When a detective stumbles upon a web of corruption that reaches the highest levels of power, he must risk everything — his career, his family, and his life — to bring justice to the city he loves.',
        genre: ['Crime', 'Thriller', 'Drama'],
        year: 2025,
        language: 'Hindi',
        duration: '2h 15min',
        rating: 8.3,
        posterUrl: '/posters/midnight-mumbai.svg',
        bannerUrl: '/posters/midnight-mumbai.svg',
        releaseDate: '2025-11-20',
        director: 'Rajesh Kapoor',
        cast: ['Arjun Reddy', 'Priya Sharma', 'Vikram Singh'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: true,
        isFeatured: false,
        status: 'published',
        views: 98200,
        createdAt: '2025-11-15',
    },
    {
        id: '3',
        title: 'The Last Samurai\'s Dream',
        description: 'An animated masterpiece that tells the story of a legendary samurai who embarks on a mystical journey through ancient Japan. With stunning visuals and a hauntingly beautiful soundtrack, this film explores themes of honor, sacrifice, and the eternal quest for inner peace.',
        genre: ['Animation', 'Adventure', 'Fantasy'],
        year: 2025,
        language: 'Japanese',
        duration: '1h 52min',
        rating: 9.1,
        posterUrl: '/posters/samurai-dream.svg',
        bannerUrl: '/posters/samurai-dream.svg',
        releaseDate: '2025-09-05',
        director: 'Hayao Tanaka',
        cast: ['Yuki Sato', 'Ken Watanabe Jr.', 'Sakura Mori'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: true,
        isFeatured: false,
        status: 'published',
        views: 203500,
        createdAt: '2025-09-01',
    },
    {
        id: '4',
        title: 'Echoes of Tomorrow',
        description: 'A mind-bending sci-fi romance where two strangers discover they can communicate across different timelines through a mysterious radio signal. As they fall in love across time, they must solve a decades-old mystery that threatens to erase their connection forever.',
        genre: ['Sci-Fi', 'Romance', 'Mystery'],
        year: 2026,
        language: 'English',
        duration: '2h 05min',
        rating: 8.5,
        posterUrl: '/posters/echoes-tomorrow.svg',
        bannerUrl: '/posters/echoes-tomorrow.svg',
        releaseDate: '2026-02-14',
        director: 'Christopher Moon',
        cast: ['Emma Sullivan', 'James Park', 'Diana Wells'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: '',
        isTrending: false,
        isFeatured: false,
        status: 'published',
        views: 67800,
        createdAt: '2026-02-10',
    },
    {
        id: '5',
        title: 'Phantom Protocol',
        description: 'An elite spy team is framed for a devastating attack they didn\'t commit. Now on the run from every intelligence agency in the world, they must uncover a shadowy organization pulling the strings from behind the scenes — before it\'s too late.',
        genre: ['Action', 'Thriller', 'Adventure'],
        year: 2025,
        language: 'English',
        duration: '2h 22min',
        rating: 8.0,
        posterUrl: '/posters/phantom-protocol.svg',
        bannerUrl: '/posters/phantom-protocol.svg',
        releaseDate: '2025-07-04',
        director: 'David Stone',
        cast: ['Ryan Blackwell', 'Sofia Martinez', 'Leo Chang'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: true,
        isFeatured: false,
        status: 'published',
        views: 156700,
        createdAt: '2025-07-01',
    },
    {
        id: '6',
        title: 'Love in Seoul',
        description: 'A heartwarming romantic comedy about an American food blogger who travels to Seoul for a culinary adventure and unexpectedly falls for a charming Korean chef. Together, they navigate cultural differences, family expectations, and the universal language of love and food.',
        genre: ['Romance', 'Comedy'],
        year: 2025,
        language: 'Korean',
        duration: '1h 48min',
        rating: 7.8,
        posterUrl: '/posters/love-seoul.svg',
        bannerUrl: '/posters/love-seoul.svg',
        releaseDate: '2025-12-25',
        director: 'Park Ji-won',
        cast: ['Kim Soo-jin', 'Rachel Green', 'Lee Min-ho'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: '',
        isTrending: false,
        isFeatured: false,
        status: 'published',
        views: 89300,
        createdAt: '2025-12-20',
    },
    {
        id: '7',
        title: 'Dark Waters Rising',
        description: 'A terrifying horror film set on a remote island where a group of marine biologists discovers an ancient underwater civilization that doesn\'t want to be found. As the waters rise and creatures from the deep emerge, survival becomes their only mission.',
        genre: ['Horror', 'Thriller', 'Mystery'],
        year: 2024,
        language: 'English',
        duration: '1h 55min',
        rating: 7.5,
        posterUrl: '/posters/dark-waters.svg',
        bannerUrl: '/posters/dark-waters.svg',
        releaseDate: '2024-10-31',
        director: 'Sarah Nightingale',
        cast: ['Tom Rivers', 'Maria Vasquez', 'James Deep'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: false,
        isFeatured: false,
        status: 'published',
        views: 112000,
        createdAt: '2024-10-25',
    },
    {
        id: '8',
        title: 'The Chennai Express 2',
        description: 'The highly anticipated sequel to the blockbuster hit returns with more action, romance, and comedy. This time, the journey takes our heroes from the beaches of Chennai to the snow-capped mountains of Kashmir in an epic cross-country adventure.',
        genre: ['Comedy', 'Action', 'Romance'],
        year: 2025,
        language: 'Tamil',
        duration: '2h 35min',
        rating: 7.9,
        posterUrl: '/posters/chennai-express.svg',
        bannerUrl: '/posters/chennai-express.svg',
        releaseDate: '2025-04-14',
        director: 'Shankar Kumar',
        cast: ['Rajini Star', 'Deepika Menon', 'Vijay Kumar'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: true,
        isFeatured: false,
        status: 'published',
        views: 245000,
        createdAt: '2025-04-10',
    },
    {
        id: '9',
        title: 'Quantum Break',
        description: 'When a quantum physics experiment goes catastrophically wrong, it tears a hole in the fabric of spacetime. A team of scientists must race against the clock to repair the breach before reality itself collapses, facing paradoxes and alternate versions of themselves.',
        genre: ['Sci-Fi', 'Action', 'Drama'],
        year: 2024,
        language: 'English',
        duration: '2h 18min',
        rating: 8.8,
        posterUrl: '/posters/quantum-break.svg',
        bannerUrl: '/posters/quantum-break.svg',
        releaseDate: '2024-06-21',
        director: 'Nolan Wright',
        cast: ['Alex Turner', 'Dr. Sarah Kim', 'Prof. David'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: '',
        isTrending: true,
        isFeatured: false,
        status: 'published',
        views: 178900,
        createdAt: '2024-06-15',
    },
    {
        id: '10',
        title: 'Whispers in the Wind',
        description: 'A powerful documentary that follows three generations of a family living in the drought-stricken regions of Rajasthan. Through stunning cinematography and intimate interviews, it reveals the resilience of the human spirit against the backdrop of climate change.',
        genre: ['Documentary', 'Drama'],
        year: 2024,
        language: 'Hindi',
        duration: '1h 42min',
        rating: 9.0,
        posterUrl: '/posters/whispers-wind.svg',
        bannerUrl: '/posters/whispers-wind.svg',
        releaseDate: '2024-08-15',
        director: 'Anita Desai',
        cast: ['Real People', 'Documentary'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: false,
        isFeatured: false,
        status: 'published',
        views: 54300,
        createdAt: '2024-08-10',
    },
    {
        id: '11',
        title: 'Dragon\'s Legacy',
        description: 'In a world where dragons once ruled the skies, a young orphan discovers she has the ancient ability to bond with these mythical creatures. With the last dragon egg in her possession, she must unite warring kingdoms before an ancient evil awakens.',
        genre: ['Fantasy', 'Adventure', 'Action'],
        year: 2026,
        language: 'English',
        duration: '2h 45min',
        rating: 8.9,
        posterUrl: '/posters/dragons-legacy.svg',
        bannerUrl: '/posters/dragons-legacy.svg',
        releaseDate: '2026-03-20',
        director: 'Peter Jackson Jr.',
        cast: ['Luna Silver', 'Draco Voice', 'King Arthur'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: 'https://t.me/+BUfqOQU5YUc1ZTc1',
        isTrending: true,
        isFeatured: false,
        status: 'published',
        views: 189500,
        createdAt: '2026-01-20',
    },
    {
        id: '12',
        title: 'La Vida Loca',
        description: 'A vibrant Spanish musical comedy that follows a retired flamenco dancer who rediscovers her passion for dance when she\'s asked to train a group of misfit teenagers for the national championship. Full of heart, humor, and incredible dance sequences.',
        genre: ['Comedy', 'Drama', 'Romance'],
        year: 2025,
        language: 'Spanish',
        duration: '2h 01min',
        rating: 7.6,
        posterUrl: '/posters/la-vida-loca.svg',
        bannerUrl: '/posters/la-vida-loca.svg',
        releaseDate: '2025-05-05',
        director: 'Carlos Rivera',
        cast: ['Isabella Cruz', 'Miguel Santos', 'Rosa Diaz'],
        watchLink: 'https://youtube.com',
        downloadLink: 'https://drive.google.com',
        telegramLink: '',
        isTrending: false,
        isFeatured: false,
        status: 'published',
        views: 43200,
        createdAt: '2025-05-01',
    },
];

// Helper to generate unique IDs
export function generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
}
